language: php

phps:
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=sqlite

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS gas_test;'; fi"
  - git submodule update --init

script: phpunit --no-globals-backup --configuration third_party/gas/tests/travis/$DB.travis.xml